// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to generate personalized recommendations for patients based on their risk factors.
 *
 * - generatePersonalizedRecommendations - A function that generates personalized recommendations for patients.
 * - PersonalizedRecommendationsInput - The input type for the generatePersonalizedRecommendations function.
 * - PersonalizedRecommendationsOutput - The return type for the generatePersonalizedRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedRecommendationsInputSchema = z.object({
  patientDataSummary: z.string().describe('A plain English summary of the patient data and key risk factors.'),
  riskLevel: z.enum(['High', 'Low']).describe('The overall risk level for the patient.'),
});
export type PersonalizedRecommendationsInput = z.infer<typeof PersonalizedRecommendationsInputSchema>;

const PersonalizedRecommendationsOutputSchema = z.object({
  recommendations: z
    .string()
    .describe(
      'Personalized recommendations for the patient to reduce their risk of readmission, formatted as markdown. Critical advice that are things to do should be marked with [DO] and things to avoid with [DON\'T]. For example: "[DO]Take your medication as prescribed." or "[DON\'T]Skip your follow-up appointments."'
    ),
});
export type PersonalizedRecommendationsOutput = z.infer<typeof PersonalizedRecommendationsOutputSchema>;

export async function generatePersonalizedRecommendations(
  input: PersonalizedRecommendationsInput
): Promise<PersonalizedRecommendationsOutput> {
  return personalizedRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizedRecommendationsPrompt',
  input: {schema: PersonalizedRecommendationsInputSchema},
  output: {schema: PersonalizedRecommendationsOutputSchema},
  prompt: `You are an expert healthcare advisor. Based on the patient's risk factors and overall risk level, provide personalized recommendations to reduce their chance of hospital readmission. Format the output as markdown.

Prefix advice that the patient **should do** with "[DO]".
Prefix advice that the patient **should not do** (or should avoid) with "[DON'T]".

Patient Data Summary: {{{patientDataSummary}}}
Risk Level: {{{riskLevel}}}

Recommendations:`,
});

const personalizedRecommendationsFlow = ai.defineFlow(
  {
    name: 'personalizedRecommendationsFlow',
    inputSchema: PersonalizedRecommendationsInputSchema,
    outputSchema: PersonalizedRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
